### ISSUE TITLE
MinSdk 14

### ISSUE THREAD

**Issue by AngleV** [shalskar/PeekAndPop#5]
Hello
I am using your amazing lib on a device with sdk 14.
OnLongClick i get the following error

```
FATAL EXCEPTION: main
                                                                   java.lang.NoClassDefFoundError: android.graphics.drawable.RippleDrawable
                                                                       at com.peekandpop.shalskar.peekandpop.PeekAnimationHelper.forceRippleAnimation(PeekAnimationHelper.java:143)
                                                                       at com.peekandpop.shalskar.peekandpop.PeekAndPop.peek(PeekAndPop.java:307)
                                                                       at com.peekandpop.shalskar.peekandpop.PeekAndPop$PeekAndPopOnTouchListener$1$1.run(PeekAndPop.java:682)
                                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:153)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5006)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

Any change to make it work for devices below API 21 ?

**Comment by shalskar** [comment]
My bad, released a patch that fixes this. Please update to version v0.1.1

compile 'com.github.shalskar:PeekAndPop:v0.1.1'

**Comment by AngleV** [comment]
@shalskar  Awesome ! it works now. Thank you
